name: Deploy pages

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Setup @antfu/ni
        run: npm i -g @antfu/ni

      - name: Install dependencies
        run: nci

      - name: Build all week*.md with correct base paths
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p dist

          BASE_PREFIX="/${{github.event.repository.name}}/" # project site

          # Find markdown entrypoints that start with "week"
          weeks=()
          while IFS= read -r -d '' f; do weeks+=("$f"); done < <(find . -maxdepth 5 -name 'week*.md' -print0 | sort -z)

          if [[ ${#weeks[@]} -eq 0 ]]; then
            echo "No week*.md files found at repo root." >&2
            exit 1
          fi

          for f in "${weeks[@]}"; do
            name="$(basename "${f%.md}")"    # e.g., week1
            out="dist/${name}"
            base="${BASE_PREFIX}${name}/"     # e.g., /repo-name/week1/
            echo "Building ${f} -> ${out} with --base ${base}"
            npx slidev build "$f" --base "$base" --out "$out"

            # ls the output folder
            echo "Contents of ./slides/$name/$out/:"
            ls -l "./slides/$name/$out/"

            # copy files from assets
            echo "Copying assets from ./slides/$name/assets/ to ./slides/$name/$out"
            cp -r "./slides/$name/assets/" "./slides/$name/$out"

            # ensure dist/name exists
            mkdir -p "dist/$name"

            # copy to the root dist folder
            cp -r "./slides/$name/$out/"* dist/$name/

            # list files in dist
            echo "Contents of dist after building $name:"
            ls -l dist/
          done

      - name: Copy existing index.html
        shell: bash
        run: |
          set -euo pipefail
          if [[ -f slides/index.html ]]; then
            cp slides/index.html dist/index.html
            echo "Copied existing index.html from slides/ to dist/"
          else
            echo "Warning: slides/index.html not found, creating basic index"
            echo "<h1>Chess Lectures</h1>" > dist/index.html
          fi

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4